[package]
name = "game_of_live"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustc-hash = "2.1.1"
wasm-bindgen = "0.2.105"


[profile.release]
debug = true
opt-level = 3
lto = false
split-debuginfo = 'unpacked'
